[package]
name = "crab"
version = "0.1.0"
edition = "2021"

[lib]
name = "crab"
crate-type = ["cdylib"]

[dependencies]
rand = "0.6.1"
rayon = "1.7.0"

[dependencies.pyo3]
version = "0.18.0"
features = ["abi3-py38"] # Must match python version as seen in `poetry env info` 
